"""empty message

Revision ID: cd4ed3e00ac3
Revises: 
Create Date: 2023-10-25 15:53:40.261089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4ed3e00ac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_value', sa.String(), nullable=True),
    sa.Column('depth_in_feet', sa.String(), nullable=True),
    sa.Column('front_in_feet', sa.String(), nullable=True),
    sa.Column('east', sa.String(), nullable=True),
    sa.Column('north', sa.String(), nullable=True),
    sa.Column('acres', sa.String(), nullable=True),
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('property_address', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('owners_name', sa.String(), nullable=True),
    sa.Column('owners_address_one', sa.String(), nullable=True),
    sa.Column('owners_address_two', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
